<?xml version="1.0" encoding="utf-8"?><Database Name="Prueba" Class="PruebaSqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-LA7PH7K\SQLEXPRESS;Initial Catalog=Prueba;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PruebaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Persona" Member="Persona">
    <Type Name="Persona">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="identificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>